---
- name: Deploy to Tomcat
  hosts: localhost
  become: yes

  tasks:

    - name: Copy war file to Tomcat
      copy:
        src: "/var/snap/jenkins/5013/workspace/2023MavenAnsible/target/2023MavenAnsible.war"
        dest: "/home/aameenasana/apache-tomcat-10.1.18/webapps/2023MavenAnsible.war"

    - name: Restart Tomcat
      shell: "/home/aameenasana/apache-tomcat-10.1.18/bin/shutdown.sh && /home/aameenasana/apache-tomcat-10.1.18/bin/startup.sh"
